spring:
   config:
      activate:
         on-profile: "prod"

build:
   version: "1.0"
   
partsandtools:
   message: "Contact Details for Parts and Tools Team for any support issues in Production"
   contactDetails:
      name: "SenthilVinayaham - ProductOwner"
      email: "senthilvinayaham@gmail.com"
   onCallSupport:
      (777) 111-2222
      (888) 333-4444